"""Development sample investment news articles.

These records are intentionally marked as sample content. They are placeholders
for local development until Sprint 009 introduces real scraper ingestion.
"""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal
from typing import Any

SAMPLE_NEWS_ARTICLES: list[dict[str, Any]] = [
    {
        "id": 1,
        "title": "Sample: ZSE market liquidity watch for retail investors",
        "summary": "Development placeholder discussing how investors might monitor turnover, breadth, and liquidity on the ZSE.",
        "content": "Sample development article only. Replace with sourced journalism or official market commentary when ingestion is implemented.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 25, 8, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.70"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": [],
    },
    {
        "id": 2,
        "title": "Sample: VFEX USD-denominated listings remain on investor watchlists",
        "summary": "Development placeholder covering general VFEX watchlist themes for USD-focused investors.",
        "content": "Sample development article only. No factual market event is asserted.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 25, 7, 30, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.68"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["SEED", "CMCL", "PHL"],
    },
    {
        "id": 3,
        "title": "Sample: RBZ policy signals and listed company planning",
        "summary": "Development placeholder for future central-bank-policy news ingestion and company impact mapping.",
        "content": "Sample development article only. Future scraper output should replace this with sourced RBZ material.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 24, 15, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.65"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": [],
    },
    {
        "id": 4,
        "title": "Sample: Delta Corporation company-news placeholder",
        "summary": "Development placeholder for future Delta-related news, filings, or analyst commentary.",
        "content": "Sample development article only. It is not a sourced company announcement.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 24, 12, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.72"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["DLTA"],
    },
    {
        "id": 5,
        "title": "Sample: Econet Wireless telecommunications watch",
        "summary": "Development placeholder for telecom-sector articles related to Econet and digital services.",
        "content": "Sample development article only. No factual operational update is asserted.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 24, 9, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.71"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["ECO"],
    },
    {
        "id": 6,
        "title": "Sample: Innscor Africa consumer-sector monitoring note",
        "summary": "Development placeholder for future consumer-sector news linked to Innscor.",
        "content": "Sample development article only. Future source attribution is required before production use.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 23, 16, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.69"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["INN"],
    },
    {
        "id": 7,
        "title": "Sample: Zimbabwe mining equities development placeholder",
        "summary": "Development placeholder for future mining-sector coverage across VFEX and ZSE-linked counters.",
        "content": "Sample development article only. It does not claim any new production or price event.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 23, 11, 30, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.67"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["CMCL"],
    },
    {
        "id": 8,
        "title": "Sample: REIT income themes for Zimbabwean investors",
        "summary": "Development placeholder covering REIT education and income-focused monitoring themes.",
        "content": "Sample development article only. It is not financial advice or a recommendation.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 23, 8, 30, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.73"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["TIGERE", "FMREIT"],
    },
    {
        "id": 9,
        "title": "Sample: Inflation context for equity research workflows",
        "summary": "Development placeholder for future inflation-linked news and analysis classification.",
        "content": "Sample development article only. Future macro data should come from official sources such as RBZ or ZIMSTAT.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 22, 14, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.66"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": [],
    },
    {
        "id": 10,
        "title": "Sample: Interest-rate sensitivity across listed sectors",
        "summary": "Development placeholder for future interest-rate news classification and sector mapping.",
        "content": "Sample development article only. It contains no sourced rate announcement.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 22, 10, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.64"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": [],
    },
    {
        "id": 11,
        "title": "Sample: Banking-sector news classification placeholder",
        "summary": "Development placeholder for future banking sector stories and asset mapping.",
        "content": "Sample development article only. No company result or regulatory event is asserted.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 21, 15, 30, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.60"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["CBZ"],
    },
    {
        "id": 12,
        "title": "Sample: Padenga Holdings VFEX monitoring placeholder",
        "summary": "Development placeholder for future Padenga-related VFEX news.",
        "content": "Sample development article only. Future ingestion must include a real source URL.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 21, 12, 30, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.62"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["PHL"],
    },
    {
        "id": 13,
        "title": "Sample: Seed Co International agriculture-sector watch",
        "summary": "Development placeholder for future agriculture and seed-business articles.",
        "content": "Sample development article only. It is not a sourced business update.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 20, 13, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.61"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["SEED"],
    },
    {
        "id": 14,
        "title": "Sample: Consumer staples sector news pipeline placeholder",
        "summary": "Development placeholder for consumer staples classification and related asset linking.",
        "content": "Sample development article only. It does not assert sector performance.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 20, 9, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.59"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["DLTA", "INN"],
    },
    {
        "id": 15,
        "title": "Sample: Exchange-rate context for market news tagging",
        "summary": "Development placeholder for future exchange-rate news and asset impact mapping.",
        "content": "Sample development article only. Official exchange-rate data must come from trusted sources when implemented.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 19, 14, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.63"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": [],
    },
    {
        "id": 16,
        "title": "Sample: Official announcements ingestion placeholder",
        "summary": "Development placeholder for future ZSE, VFEX, and issuer announcement ingestion.",
        "content": "Sample development article only. Future records should cite official announcement URLs.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 19, 10, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.58"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": [],
    },
    {
        "id": 17,
        "title": "Sample: Market breadth article placeholder",
        "summary": "Development placeholder for future market breadth and movers stories.",
        "content": "Sample development article only. No specific market movement is asserted.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 18, 16, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.57"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": [],
    },
    {
        "id": 18,
        "title": "Sample: Institutional research distribution placeholder",
        "summary": "Development placeholder for future broker or institutional research article metadata.",
        "content": "Sample development article only. Future research ingestion requires permission and attribution.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 18, 11, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.56"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": [],
    },
    {
        "id": 19,
        "title": "Sample: Commodity-linked equities monitoring placeholder",
        "summary": "Development placeholder for future commodity and mining-linked news categorization.",
        "content": "Sample development article only. It does not assert commodity price changes.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 17, 15, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.55"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": ["CMCL", "PHL"],
    },
    {
        "id": 20,
        "title": "Sample: News intelligence pipeline readiness note",
        "summary": "Development placeholder confirming the news model can later receive scraper-normalized articles.",
        "content": "Sample development article only. Sprint 009 should replace manual sample usage with scraper ingestion workflows.",
        "source": "InvestGuide Sample Data",
        "author": "InvestGuide Development",
        "published_at": datetime(2026, 6, 17, 9, 0, tzinfo=UTC),
        "url": None,
        "image_url": None,
        "language": "en",
        "sentiment": None,
        "relevance_score": Decimal("0.54"),
        "credibility_score": Decimal("0.40"),
        "asset_tickers": [],
    },
]