"""Development seed data for investment assets.

This module intentionally does not execute inserts automatically. Future database
setup scripts can import ``SEED_ASSETS`` when a configured PostgreSQL database is
available.
"""

from __future__ import annotations

from app.models.asset import AssetStatus, AssetType, Currency, Exchange

SEED_ASSETS: list[dict[str, object]] = [
    {
        "ticker": "DLTA",
        "company_name": "Delta Corporation Limited",
        "exchange": Exchange.ZSE.value,
        "sector": "Consumer Staples",
        "industry": "Beverages",
        "asset_type": AssetType.EQUITY.value,
        "currency": Currency.ZWG.value,
        "description": "Zimbabwe-listed beverages and consumer staples company.",
        "logo_url": None,
        "official_website": "https://www.delta.co.zw/",
        "market_cap": None,
        "listing_date": None,
        "status": AssetStatus.ACTIVE.value,
    },
    {
        "ticker": "ECO",
        "company_name": "Econet Wireless Zimbabwe Limited",
        "exchange": Exchange.ZSE.value,
        "sector": "Telecommunications",
        "industry": "Mobile Telecommunications",
        "asset_type": AssetType.EQUITY.value,
        "currency": Currency.ZWG.value,
        "description": "Zimbabwe-listed telecommunications operator.",
        "logo_url": None,
        "official_website": "https://www.econet.co.zw/",
        "market_cap": None,
        "listing_date": None,
        "status": AssetStatus.ACTIVE.value,
    },
    {
        "ticker": "CBZ",
        "company_name": "CBZ Holdings Limited",
        "exchange": Exchange.ZSE.value,
        "sector": "Financial Services",
        "industry": "Banking",
        "asset_type": AssetType.EQUITY.value,
        "currency": Currency.ZWG.value,
        "description": "Zimbabwe-listed financial services and banking group.",
        "logo_url": None,
        "official_website": "https://www.cbz.co.zw/",
        "market_cap": None,
        "listing_date": None,
        "status": AssetStatus.ACTIVE.value,
    },
    {
        "ticker": "INN",
        "company_name": "Innscor Africa Limited",
        "exchange": Exchange.ZSE.value,
        "sector": "Consumer Staples",
        "industry": "Food Production and Distribution",
        "asset_type": AssetType.EQUITY.value,
        "currency": Currency.ZWG.value,
        "description": "Zimbabwe-listed diversified food and consumer goods group.",
        "logo_url": None,
        "official_website": "https://www.innscorafrica.com/",
        "market_cap": None,
        "listing_date": None,
        "status": AssetStatus.ACTIVE.value,
    },
    {
        "ticker": "TIGZ",
        "company_name": "Tigere Real Estate Investment Trust",
        "exchange": Exchange.ZSE.value,
        "sector": "Real Estate",
        "industry": "REIT",
        "asset_type": AssetType.REIT.value,
        "currency": Currency.ZWG.value,
        "description": "Zimbabwe-listed real estate investment trust.",
        "logo_url": None,
        "official_website": None,
        "market_cap": None,
        "listing_date": None,
        "status": AssetStatus.ACTIVE.value,
    },
    {
        "ticker": "FMCREIT",
        "company_name": "First Mutual Properties Real Estate Investment Trust",
        "exchange": Exchange.ZSE.value,
        "sector": "Real Estate",
        "industry": "REIT",
        "asset_type": AssetType.REIT.value,
        "currency": Currency.ZWG.value,
        "description": "Real estate investment trust associated with First Mutual Properties.",
        "logo_url": None,
        "official_website": None,
        "market_cap": None,
        "listing_date": None,
        "status": AssetStatus.ACTIVE.value,
    },
    {
        "ticker": "SCIL",
        "company_name": "Seed Co International Limited",
        "exchange": Exchange.VFEX.value,
        "sector": "Consumer Staples",
        "industry": "Agriculture and Seed Production",
        "asset_type": AssetType.EQUITY.value,
        "currency": Currency.USD.value,
        "description": "VFEX-listed seed and agriculture business.",
        "logo_url": None,
        "official_website": "https://www.seedcogroup.com/",
        "market_cap": None,
        "listing_date": None,
        "status": AssetStatus.ACTIVE.value,
    },
    {
        "ticker": "CMCL",
        "company_name": "Caledonia Mining Corporation Plc",
        "exchange": Exchange.VFEX.value,
        "sector": "Basic Materials",
        "industry": "Gold Mining",
        "asset_type": AssetType.EQUITY.value,
        "currency": Currency.USD.value,
        "description": "VFEX-listed mining company with Zimbabwe gold mining operations.",
        "logo_url": None,
        "official_website": "https://www.caledoniamining.com/",
        "market_cap": None,
        "listing_date": None,
        "status": AssetStatus.ACTIVE.value,
    },
    {
        "ticker": "PHL",
        "company_name": "Padenga Holdings Limited",
        "exchange": Exchange.VFEX.value,
        "sector": "Consumer Staples",
        "industry": "Agriculture and Export Operations",
        "asset_type": AssetType.EQUITY.value,
        "currency": Currency.USD.value,
        "description": "VFEX-listed diversified agriculture and export-focused company.",
        "logo_url": None,
        "official_website": "https://www.padenga.com/",
        "market_cap": None,
        "listing_date": None,
        "status": AssetStatus.ACTIVE.value,
    },
]